---
- name: Tweaks
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    packages:
      ["tcpdump",
      "unzip",
      "screen",
      "dos2unix",
      "telnet",
      "ufw",
      "unattended-upgrades",
      "apt-listchanges",
      "atop",
      "libbison-dev",
      "libfl-dev",
      "libgcrypt20-dev",
      "libgpg-error-dev",
      "libaio-dev",
      "git-core",
      "build-essential",
      "dh-systemd",
      "autoconf",
      "libtool",
      "libusb-1.0-0-dev",
      "pkg-config",
      "libsystemd-dev",
      "libev-dev",
      "cmake",
      "mlocate",
      "snmpd",
      "snmp",
      "fake-hwclock",
      "libudev-dev",
      "libkrb5-dev",
      "libgirepository1.0-dev", # for python PygObject
      "libglib2.0-dev", # for python PygObject
      "libcairo2-dev" # for python PygObject
      ]


  tasks:
  - name: Update release
    shell: apt-get update --allow-releaseinfo-change

  - name: Update Cache
    apt: update_cache=yes

  - name: Safe apt upgrade
    apt: upgrade=safe

  - name: Upgrade Dist
    apt: upgrade=dist
    register: apt
  - debug: var=apt

  - name: install apt
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages }}"

  - name: set timezone to Central Europe
    timezone:
      name: Europe/Vienna

  - name: install english locale
    locale_gen:
      name: en_GB.UTF-8
      state: present

  - name: install locale
    locale_gen:
      name: de_DE.UTF-8
      state: present

  - name: Set locale
    command: 'update-locale LANG=de_DE.UTF-8'
    register: locale
  - debug: var=locale

  - name: keyboard
    replace:
      destfile: /etc/default/keyboard
      regexp: '"gb"'
      replace: '"de"'
    ignore_errors: yes

  - name: wpasupplicant
    copy:
      src: configs/wpa_supplicant.conf
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
      mode: 0644
      owner: root
      group: root

  - name: crda
    replace:
      destfile: /etc/default/crda
      regexp: 'REGDOMAIN='
      replace: 'REGDOMAIN=DE'
    ignore_errors: yes

  - name: regdomain
    replace:
      destfile: /lib/crda/setregdomain
      regexp: 'REGDOMAIN='
      replace: 'REGDOMAIN=DE'
    ignore_errors: yes

  - name: sap
    replace:
      destfile: /lib/systemd/system/bluetooth.service
      regexp: 'ExecStart=/usr/lib/bluetooth/bluetoothd'
      replace: 'ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap'
    ignore_errors: yes

  - name: tweak screen
    blockinfile:
      path: /etc/screenrc
      block: |
            termcapinfo xterm* ti@:te@
            startup_message off
            shell -/bin/bash

  - name: adjust timeout
    blockinfile:
      path: /etc/systemd/system.conf
      block: |
            DefaultTimeoutStartSec=150s
            DefaultTimeoutStopSec=150s

  - name: Make ssh dir
    file:
      path: /home/pi/.ssh
      state: directory
      owner: pi
      group: pi
      mode: 0600

  - name: tweak ssh
    blockinfile:
      path: /etc/ssh/ssh_config
      block: |
            ServerAliveInterval 240
            ControlMaster auto
            ControlPath ~/.ssh/ssh_mux_%h_%p_%r
            ControlPersist 448h

  - name: Make ssh root dir
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0600

  - name: Permit empty ssh
    replace:
      destfile: /etc/ssh/sshd_config
      regexp: "^#PermitEmptyPasswords no"
      replace: "PermitEmptyPasswords yes"
    ignore_errors: yes

  - name: Permit root ssh
    replace:
      destfile: /etc/ssh/sshd_config
      regexp: "^#PermitRootLogin(.*)"
      replace: "PermitRootLogin yes"
    ignore_errors: yes

  - name: Securetty
    lineinfile:
      path: /etc/securetty
      insertafter: '^console'
      line: 'ssh'

  - name: getty AMA
    systemd: masked=yes name=serial-getty@ttyAMA0.service
    ignore_errors: yes

  - name: getty S0
    systemd: masked=yes name=serial-getty@ttyS0.service
    ignore_errors: yes

  - name: Enable sshd
    systemd: enabled=yes name=ssh.service

  - name: Restart sshd
    systemd: state=restarted name=ssh

  - name: Enable network online
    systemd: enabled=yes name=systemd-networkd-wait-online.service

  - name: Pi dialout
    user:
      name: pi
      groups: sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: cmdline tty
    replace:
      destfile: /boot/cmdline.txt
      regexp: "console=serial0,115200 "
      replace: ""
    ignore_errors: yes

  - name: cmdline root
    replace:
      destfile: /boot/cmdline.txt
      regexp: "root=PARTUUID=[0-9]*[-][0-9]* +"
      replace: "root=/dev/mmcblk0p2 "
    ignore_errors: yes

  - name: Test for entry
    command: 'grep "rootdelay=5 consoleblank=0 cgroup_memory=1 cgroup_enable=memory init=/usr/lib/raspi-config/init_resize.sh" /boot/cmdline.txt'
    register: test_grep1
    ignore_errors: yes

  - name: cmdline add
    lineinfile:
      path: /boot/cmdline.txt
      backrefs: True
      state: present
      regexp: '(.*)$'
      line: '\1 rootdelay=5 consoleblank=0 cgroup_memory=1 cgroup_enable=memory init=/usr/lib/raspi-config/init_resize.sh'
    when: test_grep1.stdout == ""

  - name: edit config
    blockinfile:
      path: /boot/config.txt
      block: |
        #hdmi_safe=1
        disable_overscan=1
        hdmi_force_hotplug=1
        #hdmi_drive=2
        config_hdmi_boost=4
        #sdtv_mode=2
        dtoverlay=gpio-ir,gpio_pin=18
        dtoverlay=gpio-ir-tx,gpio_pin=17
        enable_uart=1
        #dtparam=watchdog=on

  - name: Test for entry
    shell: grep "^i2c-bcm2708" /etc/modules
    register: test_grep2
    ignore_errors: yes

  - name: Modules bcm
    lineinfile:
      path: /etc/modules
      insertafter: EOF
      line: 'i2c-bcm2708'
    when: test_grep2.stdout == ""

  - name: Create sh Group
    group:
      name: smarthome
      state: present

  - name: udev tty
    blockinfile:
      path: /etc/udev/rules.d/99-dev.rules
      create: yes
      mode: 0644
      owner: root
      group: root
      block: |
        KERNEL=="ttyS0", OWNER="root", GROUP="dialout", MODE="0660"

  - name: cronjob
    cron:
      name: udev
      user: root
      special_time: reboot
      job: 'udevadm trigger'
      cron_file: udev

  - name: Create sh User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Add groups
    user:
      name: smarthome
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout, root, tty, users
      append: yes

  - name: Make ssh dir
    file:
      path: /home/smarthome/.ssh
      state: directory
      owner: smarthome
      group: smarthome
      mode: 0700

  - name: ssh warning
    file:
      path: /etc/profile.d/sshpwd.sh
      state: absent

  - name: restart fakehwclock
    systemd: state=restarted name=fake-hwclock.service

  - name: chmod rsyslog conf
    file:
      path: /etc/rsyslog.conf
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: hostname public
    command: 'hostnamectl set-hostname SmartHomeNG'
    ignore_errors: yes

  - name: hosts public
    replace:
      destfile: /etc/hosts
      regexp: "^127.0.[0-1].1(.*)raspberrypi"
      replace: "127.0.1.1\tSmartHomeNG"
    ignore_errors: yes

  - name: Colorize
    copy:
      src: executables/mycolorize-r.sh
      dest: /usr/local/bin/colorize
      mode: 0777
      owner: root
      group: root
    register: colorize
  - debug: var=colorize

  - name: Copy colorbash
    copy:
      src: executables/colorbash.sh
      dest: /etc/profile.d/
      owner: root
      group: root
      mode: 0777

  - name: Copy tweakbash
    copy:
      src: executables/tweakbash.sh
      dest: /etc/profile.d/
      owner: root
      group: root
      mode: 0777

  - name: unalias ls pi
    replace:
      destfile: /home/pi/.bashrc
      regexp: "^\\s*[^#]alias ls='ls --color=auto'"
      replace: "#alias ls='ls --color=auto'"
    ignore_errors: yes
  - name: unalias egrep pi
    replace:
      destfile: /home/pi/.bashrc
      regexp: "^\\s*[^#]alias egrep='egrep --color=auto'"
      replace: "#alias egrep='egrep --color=auto'"
    ignore_errors: yes

  - name: unalias ls sh
    replace:
      destfile: /home/smarthome/.bashrc
      regexp: "^\\s*[^#]alias ls='ls --color=auto'"
      replace: "#alias ls='ls --color=auto'"
    ignore_errors: yes
  - name: unalias egrep sh
    replace:
      destfile: /home/smarthome/.bashrc
      regexp: "^\\s*[^#]alias egrep='egrep --color=auto'"
      replace: "#alias egrep='egrep --color=auto'"
    ignore_errors: yes

  - name: comment PS1 sh
    replace:
      destfile: /home/smarthome/.bashrc
      regexp: "^\\s*[^#]PS1="
      replace: ": #PS1="
    ignore_errors: yes

  - name: comment PS1 pi
    replace:
      destfile: /home/pi/.bashrc
      regexp: "^\\s*[^#]PS1="
      replace: ": #PS1="
    ignore_errors: yes

  - name: sudoers
    lineinfile:
      path: /etc/sudoers.d/010_smarthome-nopasswd
      create: yes
      line: 'smarthome ALL=(ALL) NOPASSWD: ALL'

  - name: Copy cleanbash
    copy:
      src: executables/cleanbash.sh
      dest: /usr/local/bin/
      mode: 0777
      owner: smarthome
      group: smarthome

  - name: disable systemslice
    blockinfile:
      path: /etc/rsyslog.d/ignore-systemd-session-slice.conf
      create: yes
      block: |
        if $programname == "systemd" and ($msg contains "Starting Session" or $msg contains "Started Session" or $msg contains "session closed" or $msg contains "session opened" or $msg contains "Created slice" or $msg contains "Starting user-" or $msg contains "Starting User Slice of" or $msg contains "Startup" or $msg contains "Removed session" or $msg contains "New session" or $msg contains "Removed slice User Slice of" or $msg contains "Stopping User Slice of" or $msg contains "dwc_otg_handle_mode_mismatch_intr") then stop
        if $programname == "systemd-logind" and ($msg contains "Starting Session" or $msg contains "Started Session" or $msg contains "session closed" or $msg contains "session opened" or $msg contains "Created slice" or $msg contains "Starting user-" or $msg contains "Starting User Slice of" or $msg contains "Removed session"  or $msg contains "New session" or $msg contains "Removed slice User Slice of" or $msg contains "Stopping User Slice of") then stop

  - name: systemd-timesyncd
    systemd: enabled=yes name=systemd-timesyncd.service

  - name: cron log
    replace:
      destfile: /etc/rsyslog.conf
      regexp: "^#cron."
      replace: "cron."
    ignore_errors: yes

  - name: cron log2
    replace:
      destfile: /etc/rsyslog.conf
      regexp: "^\\*.\\*;auth,authpriv.none"
      replace: "*.*;auth,authpriv.none;cron.none"
    ignore_errors: yes
    register: cronlog
  - debug: var=cronlog

  - name: debdir
    file: path=/etc/deb-files/ state=directory mode=0755

  - name: install checkinstall
    apt:
      name=checkinstall force=yes state=latest install_recommends=no

  - name: copy conf
    copy:
      src: configs/checkinstallrc
      dest: /usr/local/lib/checkinstall/
      mode: 0644
      owner: root

  - name: enable_fake-hwclock
    systemd: enabled=yes name=fake-hwclock.service

  - name: ufw logfile
    blockinfile:
      path: "/etc/rsyslog.d/ufw.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'ufw' or $msg contains 'UFW' then {
          action(type="omfile" file="/var/log/ufw.log" template="FileFormat_timestamp")
          stop
        }
    ignore_errors: yes

  - name: fix snmpd1
    replace:
      destfile: /etc/default/snmpd
      regexp: "export MIBS="
      replace: "#export MIBS="
    ignore_errors: yes

  - name: fix snmpd2
    replace:
      destfile: /etc/default/snmpd
      regexp: "-smux,mteTrigger,mteTriggerConf"
      replace: "-smux"
    ignore_errors: yes

  - name: rsyslog
    systemd: state=restarted name=rsyslog.service

  - name: Country Wifi
    shell: iw reg set DE

  - name: Unblock Wifi
    shell: rfkill unblock 0

  - name: Copy Update script
    copy:
      src: executables/system_update.sh
      dest: /opt/system_update
      mode: 0775
      owner: smarthome
      group: smarthome

  - name: unattended_config
    blockinfile:
      path: "/etc/apt/apt.conf.d/50unattended-upgrades"
      create: yes
      insertafter: "Unattended-Upgrade::Origins-Pattern {"
      block: |
        "o=Debian,n=${distro_codename}";
        "o=Raspbian,n=${distro_codename}";
        "origin=Raspbian,codename=${distro_codename},label=Raspbian";
        "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation";

  - name: unattended_config2
    blockinfile:
      path: "/etc/apt/apt.conf.d/20auto-upgrades"
      create: yes
      block: |
        APT::Periodic::Download-Upgradeable-Packages "0";
        APT::Periodic::AutocleanInterval "7";

  - name: unattended_config3
    replace:
      destfile: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '"1"'
      replace: '"0"'
    ignore_errors: yes

  - name: unattended_config_mail1
    replace:
      destfile: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '^//Unattended-Upgrade::Mail "";'
      replace: 'Unattended-Upgrade::Mail "root";'
    ignore_errors: yes

  - name: unattended_config_mail2
    replace:
      destfile: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '^//Unattended-Upgrade::MailOnlyOnError "false";'
      replace: 'Unattended-Upgrade::MailOnlyOnError "true";'
    ignore_errors: yes

  - name: unattended_config_removedeps
    replace:
      destfile: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies "false";'
      replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
    ignore_errors: yes

  - name: Swap
    replace:
      destfile: /etc/dphys-swapfile
      regexp: "^CONF_SWAPSIZE="
      replace: "CONF_SWAPSIZE="
    ignore_errors: yes

#  - name: Restartswap
#    systemd: state=restarted name=dphys-swapfile

  - name: Swapoff
    command: 'dphys-swapfile swapoff'

  - name: Swapdisable
    systemd: enabled=no name=dphys-swapfile

  - name: delete swap
    file:
      path: /var/swap
      state: absent
