---
- name: Install Python Packages
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    pythonremove:
      ["python3-keyring",
      "python3-pyasn1",
      "python3-keyrings.alt",
      "python3-wheel",
      "python3-setuptools",
      "python-six",
      "enum34",
      "python-idna"
      ]

    pythonremovemodules:
      ["pyxdg",
      "pycrypto",
      "astral"
      ]

    pythoninstall:
      ["RPi.GPIO",
      "pgen",
      "requests",
      "pymodbus",
      "pymysql",
      "wheel",
      "awake",
      "setuptools",
      "pycrypto",
      "yolk3k",
      "snmp",
      "knxPython",
      "spur",
      "python-miio"
      ]


  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Copy python3.8.6
    unarchive:
      src: packages/python-3.8.6_compiled.tgz
      dest: /home/smarthome
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: install python3.8.6
    make:
      chdir: /home/smarthome/python-3.8.6
      target: install

  - name: remove apt
    apt:
      name: "{{ item }}"
      state: absent
      autoremove: yes
      autoclean: yes
      purge: yes
    with_items: "{{ pythonremove }}"
    ignore_errors: yes

  - name: Add src
    replace:
      destfile: /etc/apt/sources.list
      regexp: "^#deb-src"
      replace: "deb-src"
    ignore_errors: yes

  - name: Fix
    command: 'apt-get -f -y install'

  - name: Install libffi-dev
    apt:
      name: libffi-dev
      state: latest
      install_recommends: no

  - name: Install libssl-dev
    apt:
      name: libssl-dev
      state: latest
      install_recommends: no

  - name: Install pip3
    apt:
      name: python3-pip
      state: present

  - name: remove modules
    pip:
      name: "{{ item }}"
      state: absent
      executable: pip3
    with_items: "{{ pythonremovemodules }}"

  - name: Install modules
    pip:
      name: "{{ item }}"
      executable: pip3
      state: latest
      extra_args: --user
    become: true
    become_user: smarthome
    with_items: "{{ pythoninstall }}"

  - name: pygobjectfiles
    find:
      paths: /usr/lib/python3/dist-packages/
      patterns: "pygobject*"
    register: pygobject_to_delete

  - name: Remove pygobject
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ pygobject_to_delete.files }}"
    ignore_errors: yes
    register: deleted
  - debug: var=deleted
