---
- name: Install Smartvisu
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python
    smartvisupath: /var/www/html/smartvisu2.8
    smartvisupath2: /var/www/html/smartvisu
    htmlpath: /var/www/html

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Git Smartvisu 3
    git:
      repo: 'https://github.com/Martin-Gleiss/smartvisu'
      dest: "{{ smartvisupath2 }}"
      version: master
      force: yes
    register: git
  - debug: var=git

  - name: Copy Smartvisu 2.8
    unarchive:
      remote_src: yes
      src: https://github.com/Martin-Gleiss/smartvisu/releases/download/v2.8/smartvisu-v2.8_latest.zip
      dest: /var/www/html

  - name: Remove dir
    file:
      path: /var/www/html/smartvisu2.8
      state: absent
    ignore_errors: yes

  - name: Rename sv2.8
    command: mv /var/www/html/smartvisu-master /var/www/html/smartvisu2.8

  - name: Change dir
    file:
      path: /var/www/html/smartvisu2.8
      owner: smarthome
      group: www-data
      mode: 0775
      state: directory

  - name: ignore perm2
    command: git config core.fileMode false chdir=/var/www/html/smartvisu

  - name: Change Owner
    file:
      path: "{{ htmlpath }}"
      owner: smarthome
      group: www-data
      mode: 0775
      recurse: yes
      state: directory

  - name: mbstring
    apt: name=php8.0-mbstring force=no state=latest

  - name: xml
    apt: name=php8.0-xml force=no state=latest

  - name: Restart php
    systemd: state=restarted name=php8.0-fpm.service

  - name: Restart nginx
    systemd: state=restarted name=nginx
