---
- name: Install Logcheck
  hosts: image
  remote_user: root
  become_user: root
  become: true


  tasks:
  - name: Install logcheck
    apt: name=logcheck force=no state=latest install_recommends=yes

  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout, logcheck, Debian-exim
      append: yes

  - name: change finger
    command: "chfn -f 'SmarthomeNG' logcheck"
    ignore_errors: yes

  - name: Copy logfiles
    copy:
      src: configs/logcheck.logfiles
      dest: /etc/logcheck/logcheck.logfiles
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck sh
    copy:
      src: configs/logcheck.smarthome
      dest: /etc/logcheck/ignore.d.server/local-smarthome
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck exim4
    copy:
      src: configs/logcheck.exim4
      dest: /etc/logcheck/ignore.d.server/local-exim4
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck radius
    copy:
      src: configs/logcheck.exim4
      dest: /etc/logcheck/ignore.d.server/local-radius
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck apache
    copy:
      src: configs/logcheck.exim4
      dest: /etc/logcheck/ignore.d.server/local-apache2
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck monit
    copy:
      src: configs/logcheck.monit
      dest: /etc/logcheck/ignore.d.server/local-monit
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck auth
    copy:
      src: configs/logcheck.auth
      dest: /etc/logcheck/ignore.d.server/local-auth
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck nginx
    copy:
      src: configs/logcheck.nginx
      dest: /etc/logcheck/ignore.d.server/local-nginx
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck fail2ban
    copy:
      src: configs/logcheck.fail2ban
      dest: /etc/logcheck/ignore.d.server/local-fail2ban
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck syslog
    copy:
      src: configs/logcheck.syslog
      dest: /etc/logcheck/ignore.d.server/local-syslog
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck lirc
    copy:
      src: configs/logcheck.lirc
      dest: /etc/logcheck/ignore.d.server/local-lirc
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy Logcheck mosquitto
    copy:
      src: configs/logcheck.mosquitto
      dest: /etc/logcheck/ignore.d.server/local-mosquitto
      owner: root
      group: logcheck
      mode: 0644

  - name: Groups logcheck
    user:
      name: logcheck
      groups: adm, smarthome
      append: yes

  - name: change prio
    replace:
      destfile: /etc/cron.d/logcheck
      regexp: "nice -n10"
      replace: "ionice -c3 nice -n19"
    ignore_errors: yes

  - name: change time
    replace:
      destfile: /etc/cron.d/logcheck
      regexp: "2 \\* \\* \\* \\*"
      replace: "10 * * * *"
    ignore_errors: yes

  - name: disable logcheck1
    lineinfile:
      dest: /etc/cron.d/logcheck
      regexp: '^MAILTO=root'
      line: '#MAILTO=logcheck'
      backrefs: yes
      state: present
    ignore_errors: yes

  - name: disable logcheck2
    lineinfile:
      dest: /etc/cron.d/logcheck
      regexp: '^@reboot(.*)'
      line: '#@reboot\1'
      backrefs: yes
      state: present
    ignore_errors: yes

  - name: disable logcheck3
    lineinfile:
      dest: /etc/cron.d/logcheck
      regexp: '^10(.*)'
      line: '#10\1'
      backrefs: yes
      state: present
    ignore_errors: yes
