---
- name: Install Monit
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    monitgraphpath: /var/www/html/monitgraph


  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install monit
    apt:
      name: monit
      state: latest
      update_cache: yes

  - name: Copy monitrc
    copy:
      src: configs/monitrc
      dest: /etc/monit/

  - name: Restart monit service
    systemd: state=restarted name=monit.service

  - name: Git Monitgraph
    git:
      repo: 'https://github.com/perusio/monit-graph.git'
      dest: "{{ monitgraphpath }}"
      version: master
      force: yes
    register: git
    ignore_errors: yes
  - debug: var=git

  - name: Monittoken
    file:
      path: /var/www/html/token
      owner: www-data
      group: www-data
      state: touch

  - name: Install curl
    apt: name=php-curl force=no state=latest install_recommends=yes

  - name: Copy config
    copy:
      src: configs/monitgraph.conf
      dest: "{{ monitgraphpath }}/config.php"
      mode: 0440

  - name: make dirs 0755
    command: find "{{ monitgraphpath }}" -type d ! -perm 0755 -exec chmod 0755 {} \;

  - name: make files 0644
    command: find "{{ monitgraphpath }}" -type f ! -perm 0644 -exec chmod 0644 {} \;

  - name: Change Owner
    file:
      path: "{{ monitgraphpath }}"
      owner: www-data
      group: www-data
      recurse: yes
      state: directory

  - name: data folder
    file:
      path: "{{ monitgraphpath }}/data"
      mode: 0775
      state: directory

  - name: data file
    file:
      path: "{{ monitgraphpath }}/data/index.php"
      mode: 0644
      state: touch

  - name: cronjob
    cron:
      name: monitgraph
      user: root
      job: 'php {{ monitgraphpath }}/cron.php >>/var/log/monit-graph.log >/dev/null 2>&1'
      cron_file: monitgraph

  - name: disable cron
    replace:
      destfile: /etc/cron.d/monitgraph
      regexp: "^\\*"
      replace: "#*"
    ignore_errors: yes

  - name: disable monit
    systemd: enabled=no name=monit.service

  - name: favicons
    unarchive:
      src: configs/favicons.tar
      dest: /var/www/html/favicons/
      owner: smarthome
      group: www-data
      mode: 0755
