---
- name: Install Squeezelite
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    packages_compile:
      ["libasound2-dev",
      "libflac-dev",
      "libmad0-dev",
      "libvorbis-dev",
      "libfaad-dev",
      "libmpg123-dev",
      "ffmpeg"]

    packages:
      ["ffmpeg"]

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install Packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      install_recommends: no
    with_items: "{{ packages }}"

  - name: Copy squeezelite
    copy:
      src: executables/squeezelite
      dest: /usr/bin/
      mode: 0755

  - name: Copy squeezelite sh
    copy:
      src: executables/squeezelite.sh
      dest: /usr/local/bin/
      mode: 0777

  - name: Copy squeezelite service
    copy:
      src: configs/squeezelite.service
      dest: /lib/systemd/system/

  - name: Create log file
    file:
      path: /var/log/squeezelite.log
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755
