---
- name: Install SQL
  hosts: image
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install mysql server
    apt: name=mariadb-server force=no state=latest install_recommends=yes update_cache=yes

  - name: Install mysql client
    apt: name=mariadb-client force=no state=latest install_recommends=yes
    ignore_errors: yes

  - name: Restart sql
    systemd: state=restarted name=mysql

  - name: mysql init
    blockinfile:
      path: "/root/mysqlinit"
      create: yes
      block: |
        DELETE FROM user WHERE USER = 'root' AND HOST = 'localhost';
        CREATE USER 'root'@'%' IDENTIFIED BY 'smarthome';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        CREATE DATABASE smarthome;
        CREATE USER 'smarthome'@'localhost' IDENTIFIED BY 'smarthome';
        GRANT ALL PRIVILEGES ON smarthome.* TO 'smarthome'@'localhost' WITH GRANT OPTION;
        CREATE USER 'smarthome'@'%' IDENTIFIED BY 'smarthome';
        GRANT ALL PRIVILEGES ON smarthome.* TO 'smarthome'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
    ignore_errors: yes

  - name: mysql smarthome
    shell: "mysql -uroot -proot mysql < /root/mysqlinit"
    register: init
    ignore_errors: yes
  - debug: var=init

  - name: Copy service
    copy:
      src: configs/mysql.service
      dest: /lib/systemd/system/mysql.service
      owner: root
      group: root
      mode: 0644

  - name: Install phpmyadmin
    apt:
      name: phpmyadmin
      state: latest

  - name: symlink
    file:
      src: /etc/phpmyadmin/apache.conf
      dest: /etc/apache2/conf-available/phpmyadmin.conf
      owner: root
      group: www-data
      state: link

  - name: rights
    file:
      dest: /var/lib/mysql
      owner: mysql
      group: mysql
      mode: 0770
      recurse: yes
      state: directory

  - name: conf
    copy:
      src: configs/mysql.cnf
      dest: /etc/mysql/debian.cnf
      owner: mysql
      group: mysql
      mode: 0644

  - name: link conf
    file:
      src: /etc/mysql/debian.cnf
      dest: /etc/mysql/conf.d/debian.cnf
      owner: mysql
      group: mysql
      state: link

  - name: unbind
    replace:
      destfile: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: "^bind-address"
      replace: "#bind-address"
    ignore_errors: yes

  - name: exec
    replace:
      destfile: /etc/php/7.3/apache2/php.ini
      regexp: "^max_execution_time = (.*)"
      replace: "max_execution_time = 9999"
    ignore_errors: yes

  - name: exec fpm
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: "^max_execution_time = (.*)"
      replace: "max_execution_time = 9999"
    ignore_errors: yes

  - name: memory
    replace:
      destfile: /etc/php/7.3/apache2/php.ini
      regexp: "^memory_limit = (.*)"
      replace: "memory_limit = 512M"
    ignore_errors: yes

  - name: memory fpm
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: "^memory_limit = (.*)"
      replace: "memory_limit = 512M"
    ignore_errors: yes

  - name: size
    replace:
      destfile: /etc/php/7.3/apache2/php.ini
      regexp: "^upload_max_filesize = (.*)"
      replace: "upload_max_filesize = 400M"
    ignore_errors: yes

  - name: size fpm
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: "^upload_max_filesize = (.*)"
      replace: "upload_max_filesize = 400M"
    ignore_errors: yes

  - name: postsize
    replace:
      destfile: /etc/php/7.3/apache2/php.ini
      regexp: "^post_max_size = (.*)"
      replace: "post_max_size = 400M"
    ignore_errors: yes

  - name: postsize fpm
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: "^post_max_size = (.*)"
      replace: "post_max_size = 400M"
    ignore_errors: yes

  - name: mysqli
    replace:
      destfile: /etc/php/7.3/apache2/php.ini
      regexp: "^;mysqli.allow_local_infile = On"
      replace: "mysqli.allow_local_infile = On"
    ignore_errors: yes

  - name: mysqli fpm
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: "^;mysqli.allow_local_infile = On"
      replace: "mysqli.allow_local_infile = On"
    ignore_errors: yes

  - name: phpuser
    replace:
      destfile: /etc/dbconfig-common/phpmyadmin.conf
      regexp: "^dbc_dbuser='phpmyadmin'"
      replace: "dbc_dbuser='root'"
    ignore_errors: yes

  - name: phppass
    replace:
      destfile: /etc/dbconfig-common/phpmyadmin.conf
      regexp: "^dbc_dbpass='(.*)'"
      replace: "dbc_dbpass='smarthome'"
    ignore_errors: yes

  - name: copy config
    command: /usr/sbin/dbconfig-generate-include /etc/dbconfig-common/phpmyadmin.conf /etc/phpmyadmin/config-db.php
    register: config
  - debug: var=config

  - name: Enable phpmyadmin
    command: a2enconf phpmyadmin.conf
    ignore_errors: yes
    register: a2enconf
  - debug: var=a2enconf

  - name: fix php7.3
    command: sed -i "s/|\s*\((count(\$analyzed_sql_results\['select_expr'\]\)/| (\1)/g" /usr/share/phpmyadmin/libraries/sql.lib.php
    become: true
    become_user: root
    ignore_errors: yes

  - name: fixpart2
    replace:
      destfile: /usr/share/phpmyadmin/libraries/plugin_interface.lib.php
      regexp: "if ($options != null && count($options) > 0) {"
      replace: "if ($options != null && count((array)$options) > 0) {"
    ignore_errors: yes

  - name: Restart apache
    systemd: state=restarted name=apache2
    ignore_errors: yes

  - name: Restart nginx
    systemd: state=restarted name=nginx
    ignore_errors: yes

  - name: Restart php
    systemd: state=restarted name=php7.3-fpm
    ignore_errors: yes

  - name: disable mysql
    systemd: enabled=no name=mysql.service
