---
- name: ssh_noroot
  hosts: image
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Change ssh
    replace:
      destfile: /etc/ssh/sshd_config
      regexp: "PermitRootLogin yes"
      replace: "#PermitRootLogin prohibit-password"
