---
- name: Install InfluxDB
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install
    apt:
      name: influxdb
      state: latest
      update_cache: yes

  - name: Install client
    apt:
      name: influxdb-client
      state: latest
      update_cache: yes

  - name: Install python
    pip:
      name: influxdb
      executable: pip3

  - name: conf
    blockinfile:
      dest: "/etc/influxdb/influxdb.conf"
      block: |
        [[udp]]
        enabled = true
        bind-address = ":8089"
        database = "smarthome"

  - name: Restart influxdb
    systemd: state=restarted name=influxdb.service

  - name: logfile
    blockinfile:
      dest: "/etc/rsyslog.d/influxdb.conf"
      create: yes
      block: |
        if $programname == 'influxd' then {
          action(type="omfile" file="/var/log/influxdb.log")
          stop
        }
    ignore_errors: yes

  - name: logrotate
    replace:
      destfile: /etc/logrotate.d/influxdb
      regexp: "/var/log/influxdb/influxd.log"
      replace: "/var/log/influxdb.log"

  - name: logrotate2
    lineinfile:
      path: /etc/logrotate.d/influxdb
      regexp: 'compress'
      state: absent

  - name: Create db
    shell: influx -execute "CREATE DATABASE smarthome"
    async: 40
    poll: 0
